#Service properties
server.port=9999

#Security properties
jwt.secret=sBQ4tLJ7GswrYcT47TXlRoCl7WZmTL4No8YsX2aRf44bb6NpKwAdVAXcFHQTT0NN
jwt.expiration=900000

#Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=auth-service

#Flyway properties
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=auth-service
spring.flyway.default-schema=auth-service
spring.flyway.create-schemas=true

#Database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-service?currentSchema=auth-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
