-- Schema
CREATE SCHEMA IF NOT EXISTS "auth-service";

-- Users table
CREATE TABLE IF NOT EXISTS "auth-service".users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Admin user, with password admin
INSERT INTO "auth-service".users (email, password) VALUES ('admin@gmail.com', '$2a$12$3ZPkNXBsbQQzbYPg1mRedOhpHPYfGJT0Fa/cRy5aO9sKCt2t4d8ke');
