-- Schema
CREATE SCHEMA IF NOT EXISTS "auth-service";

-- Roles table
CREATE TABLE IF NOT EXISTS "auth-service".roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(200)
);

-- Permissions table
CREATE TABLE IF NOT EXISTS "auth-service".permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(200)
);

-- Users table
CREATE TABLE IF NOT EXISTS "auth-service".users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    roles_id BIGINT       NOT NULL
);

-- Users-permissions join table
CREATE TABLE IF NOT EXISTS "auth-service".users_permissions
(
    users_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

-- Roles-permissions join table
CREATE TABLE IF NOT EXISTS "auth-service".roles_permissions
(
    roles_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

-- Constraints

ALTER TABLE "auth-service".users
    ADD CONSTRAINT fk_users_roles FOREIGN KEY (roles_id)
        REFERENCES "auth-service".roles (id);

ALTER TABLE "auth-service".users_permissions
    ADD CONSTRAINT pk_users_permissions PRIMARY KEY (users_id, permissions_id),
    ADD CONSTRAINT fk_users_permissions_users FOREIGN KEY (users_id)
        REFERENCES "auth-service".users (id),
    ADD CONSTRAINT fk_users_permissions_permissions FOREIGN KEY (permissions_id)
        REFERENCES "auth-service".permissions (id);

ALTER TABLE "auth-service".roles_permissions
    ADD CONSTRAINT pk_roles_permissions PRIMARY KEY (roles_id, permissions_id),
    ADD CONSTRAINT fk_roles_permissions_roles FOREIGN KEY (roles_id)
        REFERENCES "auth-service".roles (id),
    ADD CONSTRAINT fk_roles_permissions_permissions FOREIGN KEY (permissions_id)
        REFERENCES "auth-service".permissions (id);

-- Bulk data

INSERT INTO "auth-service".roles (name, description)
VALUES ('ADMIN', 'Role with unlimited access');

INSERT INTO "auth-service".users (email, password, roles_id)
VALUES (
    'admin@gmail.com',
    '$2a$12$3ZPkNXBsbQQzbYPg1mRedOhpHPYfGJT0Fa/cRy5aO9sKCt2t4d8ke',
    (SELECT id FROM "auth-service".roles WHERE name = 'ADMIN')
);
